# Generated by Django 2.1.5 on 2019-02-06 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoPuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_puerto', models.CharField(help_text='Nombre para agrupar los puertos (p. ej. Luces, Puertas...)', max_length=20)),
                ('grupos_con_acceso', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'ordering': ['conjunto_puerto'],
            },
        ),
        migrations.CreateModel(
            name='ConjuntoZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_zona', models.CharField(help_text='Nombre para agrupar zonas (p. ej. Baños, Despachos...)', max_length=20)),
                ('grupos_con_acceso', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'ordering': ['conjunto_zona'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rfid', models.CharField(help_text='Introduce el RFID del empleado', max_length=30, primary_key=True, serialize=False)),
                ('dentro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'rfid'],
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_puerto', models.IntegerField(help_text='Número de puerto del arduino')),
                ('descripcion', models.CharField(help_text='Acción que realiza dicho puerto', max_length=35)),
                ('encendido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['zona', 'num_puerto'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('f_entrada', models.DateTimeField()),
                ('f_salida', models.DateTimeField(blank=True, null=True)),
                ('rfid', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Empleado')),
            ],
            options={
                'ordering': ['rfid', 'ip'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='Ip del dispositivo asociado a esta aula', max_length=25)),
                ('modelo', models.CharField(help_text='Introduce el modelo del arduino (p. ej. Uno, Mega, etc.)', max_length=25)),
                ('id_zona', models.CharField(help_text='Identificador de zona (p. ej. Clase 2, Baño 4...)', max_length=25)),
                ('descripcion', models.TextField(blank=True, help_text='Introduce una descripción de la zona.', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='puerto',
            name='zona',
            field=models.ForeignKey(help_text='Zona donde se encuentra el dispositivo.', on_delete=django.db.models.deletion.CASCADE, to='catalog.Zona'),
        ),
        migrations.AddField(
            model_name='conjuntozona',
            name='zona',
            field=models.ManyToManyField(help_text='Elige las zonas que quieres agrupar', to='catalog.Zona'),
        ),
        migrations.AddField(
            model_name='conjuntopuerto',
            name='puertos',
            field=models.ManyToManyField(help_text='Elige los puertos que quieres agrupar', to='catalog.Puerto'),
        ),
        migrations.AlterUniqueTogether(
            name='puerto',
            unique_together={('zona', 'num_puerto')},
        ),
    ]
