# Generated by Django 2.1.5 on 2019-02-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoPuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_puerto', models.CharField(help_text='Nombre para agrupar los puertos (p. ej. Baños, Despachos...)', max_length=20)),
                ('grupos_con_acceso', models.ManyToManyField(to='auth.Group')),
                ('puerto', models.ManyToManyField(help_text='Elige los puertos que quieres agrupar', to='catalog.Puerto')),
            ],
            options={
                'ordering': ['conjunto_puerto'],
            },
        ),
    ]
