# Generated by Django 2.1.5 on 2019-01-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190128_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['num_zona', 'ip']},
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='num_aula',
            new_name='num_zona',
        ),
    ]
