# Generated by Django 2.1.5 on 2019-01-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_zona_dentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='dentro',
            field=models.BooleanField(default=False, help_text='La zona se encuentra ocupada o no.'),
        ),
    ]
