# Generated by Django 2.1.5 on 2019-01-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190128_1846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('ip', 'num_zona')},
        ),
    ]
