# Generated by Django 2.1.5 on 2019-01-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190128_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='encendido',
            field=models.BooleanField(default=False),
        ),
    ]
